name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main   # or master

permissions:
  pages: write      # allows the deploy action to push to the Pages environment
  id-token: write   # allows authentication for deploy-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Upload site contents for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: .      # publish everything in the repo root

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
